default:
  image: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/docker-cann:20.04-x86-8.0.0.beta1
  tags: [cpu]
  before_script:
    - pip3 config --exists-action i --user set global.index http://cmc-cd-mirror.rnd.huawei.com/pypi
    - pip3 config --exists-action i --user set global.index-url http://cmc-cd-mirror.rnd.huawei.com/pypi/simple/
    - pip3 config --exists-action i --user set global.trusted-host cmc-cd-mirror.rnd.huawei.com

stages:
   - linter
   - baselines
   - build
   - tests
   - test_all

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/
    - when: never

shell_check:
  image: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/koalaman/shellcheck-alpine:stable
  stage: linter
  dependencies: []
  before_script:
    - shellcheck --version
  script:
    - find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x

black:
  stage: linter
  image: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/python:3.9
  script:
    - pip3 install -U pip
    - pip3 install black==24.4.2 # The version here should be the same as in .pre-commit-config.yaml
    - black --check .

prospector:
  stage: linter
  image: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/python:3.9
  script:
    - pip install prospector==1.14.0
    - prospector

clang_linter:
  stage: linter
  dependencies: []
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y clang-format git-core
  script:
    - linter_errors=$(find src/ test/ -iname '*.h' -o -iname '*.cpp' | xargs clang-format -n -style=file 2>&1 || true)
    - echo "$linter_errors"
    - if [ ! -z "$linter_errors" ]; then echo "Detected formatting issues; please fix"; exit 1; else echo "Formatting is correct"; exit 0; fi

secret_detection:
  stage: linter
  dependencies: []
  before_script: []
  image:
    name: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/zricethezav/gitleaks:v8.18.2
    entrypoint: [""]
  script:
    - gitleaks detect -v --source .

pages:
  image: registry-eu.inhuawei.com:5050/zrc-von-neumann-lab/tcuscan/doxygen-alpine:latest
  stage: linter
  dependencies: []
  before_script: []
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/documentation/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public

build_spmv_eigen:
  stage: baselines
  dependencies: []
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y libeigen3-dev git-core
  script:
    - cd scripts/baselines/eigen-spmv-cpu
    - export GIT_SSL_NO_VERIFY=1 && make compile

build:
  tags:
    - baremetal
  stage: build
  before_script:
    - echo "Override script. Do not mutate pip config."
  script:
    - make setup_ci
    - make build
  artifacts:
    expire_in: 2 hours
    paths:
      - tcuscan_ops.*.so
      - build/


.test_config: &test_config
  tags:
    - baremetal
  before_script:
    - echo "Override script. Do not mutate pip config."
  stage: tests
  needs: [build]
  dependencies: [build]

test_compress:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_compress

test_copy:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_copy

test_gen_lower:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_gen_lower

test_csr_gather:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_csr_gather

test_diff:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_diff

test_mcscan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_multi_core

test_mcscan_no_l2:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_multi_core_no_l2


test_scan_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_single_core

test_scan_batch:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_batch

test_seg_scan_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_single_core

test_seg_scan_vec_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_vec_single_core

test_segmented_sum:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_segmented_sum

test_seg_scan_mc_revert:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_mc_revert

test_split:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_split

test_split_ind:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_split_ind

test_radix_sort:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_radix_sort

test_vadd:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_vadd

test_mcgather:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_mc_gather

test_gather_spmv:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_gather_spmv

test_spmv:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_spmv

test_matmul_cce:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_matmul_cce

test_row_scan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_row_scan

test_reduce_tiles:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_reduce_tiles

test_complete_rows:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_complete_rows

test_simple_pad:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_simple_pad

test_block_scan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_block_scan

test_complete_blocks:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_complete_blocks

# Uncomment to run all tests in a single run
unit_test:
  tags:
    - baremetal
  stage: test_all
  dependencies: []
  before_script:
    - echo "Override script. Do not mutate pip config."
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make build test
  rules:
    - if: '$CI_RUN_LONG_TESTS == "1"'
    - when: manual
      allow_failure: true
