default:
  image: quay.io/ascend/cann:9.0.0-910b-ubuntu22.04-py3.11
  tags: [cpu]

stages:
   - linter
   - baselines
   - build
   - tests
   - test_all

# Define the workflow rules manually to make sure only a single pipeline
# is created for each MR update. Without that, GitLab creates one pipeline
# for branch update and one for MR update.
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

shell_check:
  image: koalaman/shellcheck-alpine:stable
  stage: linter
  dependencies: []
  before_script:
    - shellcheck --version
  script:
    - find . -type f -name '*.sh' -print0 | xargs -0 shellcheck -x

black:
  stage: linter
  image: python:3.9
  script:
    - pip3 install -U pip
    - pip3 install black==25.1.0 # The version here should be the same as in .pre-commit-config.yaml
    - black --check .

cmake_linter:
  stage: linter
  image: python:3.9
  script:
    - pip3 install -U pip cmakelang
    - cmake-lint CMakeLists.txt

prospector:
  stage: linter
  image: python:3.9
  script:
    - pip install prospector==1.14.0
    - prospector

clang_linter:
  stage: linter
  dependencies: []
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y clang-format git-core
  script:
    - linter_errors=$(find src/ -iname '*.h' -o -iname '*.cpp' | xargs clang-format -n -style=file 2>&1 || true)
    - echo "$linter_errors"
    - if [ ! -z "$linter_errors" ]; then echo "Detected formatting issues; please fix"; exit 1; else echo "Formatting is correct"; exit 0; fi


clang_tidy:
  stage: linter
  dependencies: []
  needs: []
  script:
    - make clang_tidy

secret_detection:
  stage: linter
  dependencies: []
  before_script: []
  image:
    name: zricethezav/gitleaks:v8.18.2
    entrypoint: [""]
  script:
    - gitleaks detect -v --source .

pages:
  image: zouzias/doxygen:latest
  stage: linter
  dependencies: []
  before_script: []
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/documentation/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public

build_spmv_eigen:
  stage: baselines
  dependencies: []
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y libeigen3-dev git-core
  script:
    - cd scripts/baselines/eigen-spmv-cpu
    - export GIT_SSL_NO_VERIFY=1 && make compile

build:
  tags:
    - docker_npu
  stage: build
  before_script:
    - echo "Override script. Do not mutate pip config."
  script:
    - make setup_ci
    - make build
  artifacts:
    expire_in: 2 hours
    paths:
      - tcuscan_ops.*.so
      - build/


.test_config: &test_config
  tags:
    - baremetal
  before_script:
    - echo "Override script. Do not mutate pip config."
  stage: tests
  needs: [build]
  dependencies: [build]

test_compress:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_compress

test_compress_pos:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_compress_pos

test_compress_ind:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_compress_ind

test_copy:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_copy

test_gen_lower:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_gen_lower

test_csr_gather:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_csr_gather

test_diff:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_diff

test_mcscan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_multi_core

test_mcscan_no_l2:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_multi_core_no_l2

test_scan_cpu:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_cpu


test_scan_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_single_core

test_scan_batch:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_batch

test_seg_scan_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_single_core

test_seg_scan_vec_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_vec_single_core

test_segmented_sum:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_segmented_sum

test_seg_sum_single_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_sum_single_core

test_seg_sum_multi_core:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_sum_multi_core

test_seg_sum_single_cube:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_sum_single_cube

test_seg_scan_mc_revert:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_seg_scan_mc_revert

test_split:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_split

test_split_ind:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_split_ind

test_topk:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_topk

test_topk_pivot:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_topk_pivot

test_radix_sort:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_radix_sort

test_vadd:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_vadd

test_mcgather:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_mc_gather

test_gather_spmv:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_gather_spmv

test_spmv:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_spmv

test_spmv_multi_cube:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_spmv_multi_cube


test_matmul_cce:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_matmul_cce

test_row_scan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_row_scan

test_reduce_tiles:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_reduce_tiles

test_cube_reduce:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_cube_reduce

test_complete_rows:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_complete_rows

test_simple_pad:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_simple_pad

test_block_scan:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_block_scan

test_complete_blocks:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_complete_blocks

test_scan_multi_cube:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_scan_multi_cube

test_tri_inv_col_sweep:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_tri_inv_col_sweep

test_tri_inv_cube_col_sweep:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_tri_inv_cube_col_sweep

test_triu_inv_rec_unroll:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_triu_inv_rec_unroll

test_count_if:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_count_if

test_filter_greater_equal:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_filter_greater_equal

test_where:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_where

test_compress_ind_no_arange:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_compress_ind_no_arange

test_histogram:
  <<: *test_config
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make test_histogram


# Uncomment to run all tests in a single run
unit_test:
  tags:
    - docker_npu
  stage: test_all
  dependencies: []
  before_script:
    - echo "Override script. Do not mutate pip config."
  script:
    - make setup_ci
    - source /usr/local/Ascend/ascend-toolkit/set_env.sh && make build test
  rules:
    - if: '$CI_RUN_LONG_TESTS == "1"'
    - when: manual
      allow_failure: true
