#!/usr/bin/env python3


import argparse

import jinja2
from jinja2 import FileSystemLoader


def camel(snake_str):
    items = snake_str.split("_")
    return "".join([*map(str.title, items)])


def main():

    parser = argparse.ArgumentParser(
        prog="gen_new_kernel",
        description="Generates a new vector-only AscendC kernel",
        epilog="Generates all files on the current directory. Use `make deploy` to place the files in the correct location in the repo.",
    )

    parser.add_argument(
        "-n",
        "--name",
        help="Name of the autogenerated kernel in snake_case, i.e., awe_some.",
        type=str,
    )

    parser.add_argument(
        "-ns",
        "--cpp_namespace",
        help="Name of C++ namespace to use.",
        type=str,
    )

    args = parser.parse_args()
    cpp_namespace = args.cpp_namespace
    kernel_cpp_name = args.name.lower()
    assert (
        len(kernel_cpp_name) > 3
    ), f"The kernel name must have at least 3 characters. Got {kernel_cpp_name}"

    env = jinja2.Environment(loader=FileSystemLoader("templates/"))

    metadata = {
        "kernel_name": f"Vector {kernel_cpp_name}",
        "kernel_cpp_name": kernel_cpp_name,
        "kernel_class_name": f"Kernel{camel(kernel_cpp_name)}",
        "kernel_cpp_name_suffix": camel(kernel_cpp_name),
        "kernel_dtype": "half",
        "kernel_desc_short": f"Vector {kernel_cpp_name} kernel",
        "kernel_desc_long": "Returns np.awesomeXXX(x) for a vector x",
        "copyright_year": "2025",
        "num_blocks": "8",
        "cpp_namespace": cpp_namespace,
    }

    enc = "utf-8"

    kernel = env.get_template("kernel_vec.h.j2")
    kernel_contents = kernel.render(**metadata)
    with open(f"kernel_{kernel_cpp_name}.h", "w", encoding=enc) as fd:
        fd.write(kernel_contents)

    tiling = env.get_template("tiling.h.j2")
    tiling_contents = tiling.render(**metadata)
    with open(f"tiling_{kernel_cpp_name}.h", "w", encoding=enc) as fd:
        fd.write(tiling_contents)

    kernel_runner = env.get_template("kernel.cpp.j2")
    kernel_cpp_contents = kernel_runner.render(**metadata)
    with open(f"kernel_{kernel_cpp_name}.cpp", "w", encoding=enc) as fd:
        fd.write(kernel_cpp_contents)

    torch_template = env.get_template("torch.h.j2")
    torch_contents = torch_template.render(**metadata)
    with open(f"torch_{kernel_cpp_name}.h", "w", encoding=enc) as fd:
        fd.write(torch_contents)

    pytest_template = env.get_template("pytest.py.j2")
    pytest_contents = pytest_template.render(**metadata)
    with open(f"test_{kernel_cpp_name}.py", "w", encoding=enc) as fd:
        fd.write(pytest_contents)


if __name__ == "__main__":
    main()
